# Generated by Django 2.0.5 on 2018-05-23 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('msg', models.TextField()),
                ('isread', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('filter', models.CharField(max_length=100)),
                ('chart', models.CharField(max_length=100)),
                ('variable', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
                ('threshold', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('to', models.CharField(max_length=1000)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warning.Rule'),
        ),
    ]
