# Generated by Django 2.0.5 on 2018-05-24 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='url',
            new_name='module',
        ),
    ]
